USE tpcc;
CREATE TABLE WAREHOUSE (
  W_ID SMALLINT DEFAULT '0' NOT NULL,
  W_NAME VARCHAR(16),
  W_STREET_1 VARCHAR(32),
  W_STREET_2 VARCHAR(32),
  W_CITY VARCHAR(32),
  W_STATE VARCHAR(2),
  W_ZIP VARCHAR(9),
  W_TAX FLOAT,
  W_YTD FLOAT
);

CREATE TABLE DISTRICT (
  D_ID TINYINT DEFAULT '0' NOT NULL,
  D_W_ID SMALLINT DEFAULT '0' NOT NULL,
  D_NAME VARCHAR(16),
  D_STREET_1 VARCHAR(32),
  D_STREET_2 VARCHAR(32),
  D_CITY VARCHAR(32),
  D_STATE VARCHAR(2),
  D_ZIP VARCHAR(9),
  D_TAX FLOAT,
  D_YTD FLOAT,
  D_NEXT_O_ID INT,
  PRIMARY KEY (D_W_ID,D_ID)
);

CREATE TABLE ITEM (
  I_ID INTEGER DEFAULT '0' NOT NULL,
  I_IM_ID INTEGER,
  I_NAME VARCHAR(32),
  I_PRICE FLOAT,
  I_DATA VARCHAR(64)
);

CREATE TABLE CUSTOMER (
  C_ID INTEGER DEFAULT '0' NOT NULL,
  C_D_ID TINYINT DEFAULT '0' NOT NULL,
  C_W_ID SMALLINT DEFAULT '0' NOT NULL,
  C_FIRST VARCHAR(32),
  C_MIDDLE VARCHAR(2),
  C_LAST VARCHAR(32),
  C_STREET_1 VARCHAR(32),
  C_STREET_2 VARCHAR(32),
  C_CITY VARCHAR(32),
  
  C_STATE VARCHAR(2),
  C_ZIP VARCHAR(9),
  C_PHONE VARCHAR(32),
  C_SINCE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  C_CREDIT VARCHAR(2),
  C_CREDIT_LIM FLOAT,
  C_DISCOUNT FLOAT,

  C_BALANCE FLOAT,
  C_YTD_PAYMENT FLOAT,
  C_PAYMENT_CNT INTEGER,
  C_DELIVERY_CNT INTEGER,
  C_DATA VARCHAR(500),
  PRIMARY KEY (C_W_ID,C_D_ID,C_ID)
);
CREATE INDEX IDX_CUSTOMER ON CUSTOMER (C_W_ID,C_D_ID,C_LAST);

CREATE TABLE HISTORY (
  H_C_ID INTEGER,
  H_C_D_ID TINYINT,
  H_C_W_ID SMALLINT,
  H_D_ID TINYINT,
  H_W_ID SMALLINT DEFAULT '0' NOT NULL,
  H_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  H_AMOUNT FLOAT,
  H_DATA VARCHAR(32)
);

CREATE TABLE STOCK (
  S_I_ID INTEGER DEFAULT '0' NOT NULL,
  S_W_ID SMALLINT DEFAULT '0 ' NOT NULL,
  S_QUANTITY INTEGER DEFAULT '0' NOT NULL,
  S_DIST_01 VARCHAR(32),
  S_DIST_02 VARCHAR(32),
  S_DIST_03 VARCHAR(32),
  S_DIST_04 VARCHAR(32),
  S_DIST_05 VARCHAR(32),
  S_DIST_06 VARCHAR(32),
  S_DIST_07 VARCHAR(32),
  S_DIST_08 VARCHAR(32),
  S_DIST_09 VARCHAR(32),
  S_DIST_10 VARCHAR(32),
  S_YTD INTEGER,
  S_ORDER_CNT INTEGER,
  S_REMOTE_CNT INTEGER,
  S_DATA VARCHAR(64),
  PRIMARY KEY (S_W_ID,S_I_ID)
);

CREATE TABLE ORDERS (
  O_ID INTEGER DEFAULT '0' NOT NULL,
  O_C_ID INTEGER,
  O_D_ID TINYINT DEFAULT '0' NOT NULL,
  O_W_ID SMALLINT DEFAULT '0' NOT NULL,
  O_ENTRY_D TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  O_CARRIER_ID INTEGER,
  O_OL_CNT INTEGER,
  O_ALL_LOCAL INTEGER,
  PRIMARY KEY (O_W_ID,O_D_ID,O_ID)
);
CREATE INDEX IDX_ORDERS ON ORDERS (O_W_ID,O_D_ID,O_C_ID);

CREATE TABLE NEW_ORDER (
  NO_O_ID INTEGER DEFAULT '0' NOT NULL,
  NO_D_ID TINYINT DEFAULT '0' NOT NULL,
  NO_W_ID SMALLINT DEFAULT '0' NOT NULL
);

CREATE TABLE ORDER_LINE (
  OL_O_ID INTEGER DEFAULT '0' NOT NULL,
  OL_D_ID TINYINT DEFAULT '0' NOT NULL,
  OL_W_ID SMALLINT DEFAULT '0' NOT NULL,
  OL_NUMBER INTEGER DEFAULT '0' NOT NULL,
  OL_I_ID INTEGER,
  OL_SUPPLY_W_ID SMALLINT,
  OL_DELIVERY_D TIMESTAMP,
  OL_QUANTITY INTEGER,
  OL_AMOUNT FLOAT,
  OL_DIST_INFO VARCHAR(32),
  PRIMARY KEY (OL_W_ID,OL_D_ID,OL_O_ID,OL_NUMBER)
);

CREATE INDEX IDX_ORDER_LINE_TREE ON ORDER_LINE (OL_W_ID,OL_D_ID,OL_O_ID);
