USE tpcc
CREATE TABLE CUSTOMER (
  C_W_ID INT ,
  C_D_ID INT ,
  C_ID INT ,
  C_DISCOUNT DECIMAL(4,4) ,
  C_CREDIT CHAR(2) ,
  C_LAST VARCHAR(16) ,
  C_FIRST VARCHAR(16) ,
  C_CREDIT_LIM DECIMAL(12,2) ,
  C_BALANCE DECIMAL(12,2) ,
  C_YTD_PAYMENT FLOAT ,
  C_PAYMENT_CNT INT ,
  C_DELIVERY_CNT INT ,
  C_STREET_1 VARCHAR(20) ,
  C_STREET_2 VARCHAR(20) ,
  C_CITY VARCHAR(20) ,
  C_STATE CHAR(2) ,
  C_ZIP CHAR(9) ,
  C_PHONE CHAR(16) ,
  C_SINCE TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
  C_MIDDLE CHAR(2) ,
  C_DATA VARCHAR(500) ,
  PRIMARY KEY (C_W_ID,C_D_ID,C_ID)
);


CREATE TABLE DISTRICT (
  D_W_ID INT ,
  D_ID INT ,
  D_YTD DECIMAL(12,2) ,
  D_TAX DECIMAL(4,4) ,
  D_NEXT_O_ID INT ,
  D_NAME VARCHAR(10) ,
  D_STREET_1 VARCHAR(20) ,
  D_STREET_2 VARCHAR(20) ,
  D_CITY VARCHAR(20) ,
  D_STATE CHAR(2) ,
  D_ZIP CHAR(9) ,
  PRIMARY KEY (D_W_ID,D_ID)
);

-- TODO: H_DATE ON UPDATE CURRENT_TIMESTAMP

CREATE TABLE HISTORY (
  H_C_ID INT ,
  H_C_D_ID INT ,
  H_C_W_ID INT ,
  H_D_ID INT ,
  H_W_ID INT ,
  H_DATE TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
  H_AMOUNT DECIMAL(6,2) ,
  H_DATA VARCHAR(24) 
);


CREATE TABLE ITEM (
  I_ID INT ,
  I_NAME VARCHAR(24) ,
  I_PRICE DECIMAL(5,2) ,
  I_DATA VARCHAR(50) ,
  I_IM_ID INT ,
  PRIMARY KEY (I_ID)
);


CREATE TABLE NEW_ORDER (
  NO_W_ID INT ,
  NO_D_ID INT ,
  NO_O_ID INT ,
  PRIMARY KEY (NO_W_ID,NO_D_ID,NO_O_ID)
);

CREATE TABLE ORDERS (
  O_W_ID INT ,
  O_D_ID INT ,
  O_ID INT ,
  O_C_ID INT ,
  O_CARRIER_ID INT DEFAULT NULL,
  O_OL_CNT DECIMAL(2,0) ,
  O_ALL_LOCAL DECIMAL(1,0) ,
  O_ENTRY_D TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (O_W_ID,O_D_ID,O_ID),
  UNIQUE (O_W_ID,O_D_ID,O_C_ID,O_ID)
);


CREATE TABLE ORDER_LINE (
  OL_W_ID INT ,
  OL_D_ID INT ,
  OL_O_ID INT ,
  OL_NUMBER INT ,
  OL_I_ID INT ,
  OL_DELIVERY_D TIMESTAMP NULL DEFAULT NULL,
  OL_AMOUNT DECIMAL(6,2) ,
  OL_SUPPLY_W_ID INT ,
  OL_QUANTITY DECIMAL(2,0) ,
  OL_DIST_INFO CHAR(24) ,
  PRIMARY KEY (OL_W_ID,OL_D_ID,OL_O_ID,OL_NUMBER)
);

CREATE TABLE STOCK (
  S_W_ID INT ,
  S_I_ID INT ,
  S_QUANTITY DECIMAL(4,0) ,
  S_YTD DECIMAL(8,2) ,
  S_ORDER_CNT INT ,
  S_REMOTE_CNT INT ,
  S_DATA VARCHAR(50) ,
  S_DIST_01 CHAR(24) ,
  S_DIST_02 CHAR(24) ,
  S_DIST_03 CHAR(24) ,
  S_DIST_04 CHAR(24) ,
  S_DIST_05 CHAR(24) ,
  S_DIST_06 CHAR(24) ,
  S_DIST_07 CHAR(24) ,
  S_DIST_08 CHAR(24) ,
  S_DIST_09 CHAR(24) ,
  S_DIST_10 CHAR(24) ,
  PRIMARY KEY (S_W_ID,S_I_ID)
);

CREATE TABLE WAREHOUSE (
  W_ID INT ,
  W_YTD DECIMAL(12,2) ,
  W_TAX DECIMAL(4,4) ,
  W_NAME VARCHAR(10) ,
  W_STREET_1 VARCHAR(20) ,
  W_STREET_2 VARCHAR(20) ,
  W_CITY VARCHAR(20) ,
  W_STATE CHAR(2) ,
  W_ZIP CHAR(9) ,
  PRIMARY KEY (W_ID)
);
